### PR TITLE
Fix for 64-bit

### PR DESCRIPTION
**Pull request by dscho**
This is by necessity still incomplete a fix because it is technically
possible to have an MSys2 installation in other locations than C:\msys32
or C:\msys64, but it will have to do for now.

Signed-off-by: Johannes Schindelin johannes.schindelin@gmx.de

### CODE REVIEW

**Comment by dscho** [comment]
Okay, I finally figured out what caused that segmentation violation here. It was that off-by-one, where `convert()` was called with a `dstlen` that was actually the buffer capacity, not the maximal string length.

**Comment by dscho** [comment]
Thanks!

**Comment by Alexpux** [comment]
Please backport here patches that is applied to msys2-runtime too

**Comment by dscho** [comment]
> Please backport here patches that is applied to msys2-runtime too

What do you mean? Are you asking for Pull Requests that make the tests pass for things like usertemp, Git for Windows support, etc? If so, I just opened another [Pull Request](https://github.com/Alexpux/path_convert/pull/2) corresponding to the usertemp Pull Request in msys2-runtime.

Or do you mean something different?

**Comment by Alexpux** [comment]
I'm about commits:
https://github.com/Alexpux/Cygwin/commit/4152199c2a8b370b6cd6bdb54a102f57e039759b
https://github.com/Alexpux/Cygwin/commit/a94de842a87d5f8adfb38934ecee5931ced2d089

**Comment by dscho** [comment]
Ah! Will do so tomorrow.

**Comment by dscho** [comment]
See https://github.com/Alexpux/path_convert/pull/3 (will _test_ tomorrow :smiley: )

**Pull request merged**
